services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pagemachine\Phinx\:
    resource: '../Classes/*'

  Pagemachine\Phinx\Command\CreateCommand:
    tags:
      - name: console.command
        command: phinx:create
        schedulable: false
  Pagemachine\Phinx\Command\MigrateCommand:
    tags:
      - name: console.command
        command: phinx:migrate
        schedulable: false
  Pagemachine\Phinx\Command\RollbackCommand:
    tags:
      - name: console.command
        command: phinx:rollback
        schedulable: false
  Pagemachine\Phinx\Command\StatusCommand:
    tags:
      - name: console.command
        command: phinx:status
        schedulable: false
  Pagemachine\Phinx\Command\SeedCreateCommand:
    tags:
      - name: console.command
        command: phinx:seed:create
        schedulable: false
  Pagemachine\Phinx\Command\SeedRunCommand:
    tags:
      - name: console.command
        command: phinx:seed:run
        schedulable: false
